import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Provider from "@/providers/session-provider";
import { getSession } from "next-auth/react";
import QueryProvider from "@/providers/query-client";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();
  return (
    <html lang="en">
      <QueryProvider>
        <Provider session={session}>
          <body className={`${inter.className} ${poppins.className}`}>
            {children}
          </body>
        </Provider>
      </QueryProvider>
    </html>
  );
}
