import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/providers/session-provider'
import { getSession } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getSession();
  return (
    <html lang="en">
      <Provider session={session}>
      <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  )
}
